import React from 'react'

import Head from 'next/head'

import Intro from '../components/Intro'
import Skills from '../components/Skills'
import Project from '../components/Projects/Project'

export default function Home({ about, projects, skills }) {

  return (
    <div className=''>
      <Head>
        <title>Nam Le</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro about={about[0]} />
      <Skills skills={skills} />
      <Project project={projects} />
    </div>
  )
}


export async function getServerSideProps() {

  const API = 'https://namnomdev.vercel.app'

  const [projectsRes, aboutRes, skillsRes] = await Promise.all([
    fetch('https://namnomdev.vercel.app/api/projects'),
    fetch('https://namnomdev.vercel.app/api/about'),
    fetch('https://namnomdev.vercel.app/api/skills')
  ])
  
  const [projects, about, skills] = await Promise.all([
    projectsRes.json(),
    aboutRes.json(),
    skillsRes.json(),

  ])
  

  return {
      props: {
          projects,
          about,
          skills,
      },
  }
}
