import React from 'react'

import Head from 'next/head'

import Intro from '../components/Intro'
import Project from '../components/Projects/Project'

export default function Home({ about, projects }) {

  return (
    <div className=''>
      <Head>
        <title>Nam Le</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Intro about={about[0]} />
      <Project project={projects} />
    </div>
  )
}


export async function getServerSideProps() {

  const API = 'https://namnomdev.vercel.app'

  const [projectsRes, aboutRes] = await Promise.all([
    fetch('http://localhost:3000/api/projects'),
    fetch('http://localhost:3000/api/about')
  ])
  
  const [projects, about] = await Promise.all([
    projectsRes.json(),
    aboutRes.json()
  ])
  

  return {
      props: {
          projects,
          about
      },
  }
}
